version: '3.7'

services:
  facundia:
    image: node:10.18.1
    container_name: facundia
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./volumes:/usr/src/app
    command: "/bin/sh -c 'cd /usr/src/app/server; npm ci; cd /usr/src/app/server; npm ci; npm run start:prod'"
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./volumes/client/dist:/var/www/html